module.exports = { content: ['./*.html', './*.js'], 
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "inverse-primary": "#855300",
                    "inverse-on-surface": "#2a3043",
                    "on-tertiary-fixed": "#07006c",
                    "on-primary-container": "#613b00",
                    "on-tertiary-fixed-variant": "#2f2ebe",
                    "surface-container-high": "#23293c",
                    "secondary": "#4edea3",
                    "background": "#0c1324",
                    "on-primary-fixed-variant": "#653e00",
                    "surface-container-highest": "#2e3447",
                    "secondary-container": "#00a572",
                    "on-secondary-container": "#00311f",
                    "on-primary-fixed": "#2a1700",
                    "primary-fixed": "#ffddb8",
                    "outline-variant": "#534434",
                    "tertiary-fixed": "#e1e0ff",
                    "tertiary": "#c7c8ff",
                    "error": "#ffb4ab",
                    "on-error": "#690005",
                    "on-secondary": "#003824",
                    "surface-container-low": "#151b2d",
                    "tertiary-fixed-dim": "#c0c1ff",
                    "on-surface-variant": "#d8c3ad",
                    "on-surface": "#dce1fb",
                    "error-container": "#93000a",
                    "surface-variant": "#2e3447",
                    "surface-tint": "#ffb95f",
                    "on-primary": "#472a00",
                    "tertiary-container": "#a7a9ff",
                    "on-secondary-fixed-variant": "#005236",
                    "primary": "#ffc174",
                    "secondary-fixed-dim": "#4edea3",
                    "primary-container": "#f59e0b",
                    "surface-container": "#191f31",
                    "secondary-fixed": "#6ffbbe",
                    "on-tertiary": "#1000a9",
                    "surface-dim": "#0c1324",
                    "surface": "#0c1324",
                    "inverse-surface": "#dce1fb",
                    "on-error-container": "#ffdad6",
                    "surface-bright": "#33394c",
                    "primary-fixed-dim": "#ffb95f",
                    "outline": "#a08e7a",
                    "on-secondary-fixed": "#002113",
                    "surface-container-lowest": "#070d1f",
                    "on-background": "#dce1fb",
                    "on-tertiary-container": "#2b29bb"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "margin-mobile": "16px",
                    "gutter": "24px",
                    "margin-desktop": "40px",
                    "container-max": "1280px",
                    "base": "8px"
            },
            "fontFamily": {
                    "label-sm": ["JetBrains Mono"],
                    "headline-md": ["Inter"],
                    "body-lg": ["Inter"],
                    "headline-lg": ["Inter"],
                    "label-md": ["JetBrains Mono"],
                    "headline-lg-mobile": ["Inter"],
                    "display-xl": ["Inter"],
                    "body-md": ["Inter"]
            },
            "fontSize": {
                    "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                    "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                    "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
                    "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "headline-lg-mobile": ["28px", {"lineHeight": "34px", "fontWeight": "800"}],
                    "display-xl": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "900"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
          },
        },
       plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')]}